# Generated by Django 5.0.7 on 2024-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("items", models.TextField()),
                ("lat_long", models.FloatField()),
                ("full_details", models.TextField()),
            ],
        ),
    ]
