# Generated by Django 5.0.7 on 2024-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="lat_long",
            new_name="latitude",
        ),
        migrations.AddField(
            model_name="dish",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
