# Generated by Django 5.0.7 on 2024-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_rename_lat_long_dish_latitude_dish_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
